monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]

        mail:
            type: fingers_crossed
            action_level: error
            excluded_http_codes: [ 400, 403, 404 ]
            handler: deduplicated
        deduplicated:
            type: deduplication
            handler: mailer
        mailer:
            type: symfony_mailer
            from_email: '%env(resolve:EMAIL_SENDER)%'
            to_email: '%env(EMERGENCY_EMAIL)%'
            subject: 'An Error Occurred! %%message%%'